### PR TITLE
Fixes for class progression table and misc item/spell/stablock issues

### LINKED ISSUE #625: 🐛 Text error in items granting resistance
### Describe the bug

Items that grant resistance to a damage type display `{{getFullImmRes item.resist}}` in their text block instead of the associated damage type. See attached file for example.

[armor-of-acid-resistance-xdmg.md](https://github.com/user-attachments/files/18594995/armor-of-acid-resistance-xdmg.md)

### Expected Behavior

The resisted damage type should be rendered in plaintext in item descriptions.

### TTRPG CLI Version

3.0.0

### Which Operating Systems have you experienced this on?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [x] Windows

### LINKED ISSUE #628: 🐛 Emanation spells have no range text
### Describe the bug

Spells with the new Emanation AoE type have no text for their Range field (example attached). Very minor bug.

[spirit-guardians-xphb.md](https://github.com/user-attachments/files/18627495/spirit-guardians-xphb.md)

### Expected Behavior

The Range field for Emanation spells should read something like:

- **Range:** Self (30-foot Emanation)

### TTRPG CLI Version

3.0.1

### Which Operating Systems have you experienced this on?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [x] Windows

### LINKED ISSUE #655: 🐛 Missing text in attack actions in XMM statblocks
### Describe the bug

Monster statblock actions that involve attack rolls use the format "_Melee/Ranged Attack Roll_" as of the XMM release. These sections used to follow the format "_Melee/Ranged Weapon/Spell Attack_" and as such the tool seems to adhere to that legacy text format and drop the word "Roll" when populating a yaml statblock. See example attached.

[displacer-beast-xmm.md](https://github.com/user-attachments/files/18804461/displacer-beast-xmm.md)

### Expected Behavior

Statblocks from the 2024+ rules should all have the phrase structure "_Melee/Ranged Attack Roll_" in any of their actions that detail an attack roll. The word "Roll" should not be removed.

### TTRPG CLI Version

3.0.1

### Which Operating Systems have you experienced this on?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [x] Windows

### LINKED ISSUE #672: 🐛 5e Class Progression Anchor Links nor resolving
### Describe the bug

Using ttrpg-convert.exe version 3.0.1 on Windows 11, after importing the 5e PHB (2014 or 2024) successfully, on the Class pages, the Class Progression table has links to the headings further down the page to the various class features that unlock at each level.

### Expected Behavior

Using the stock import templates, the links do not resolve when clicked. It appears they should jump you down to those sections of the class page, but they do nothing.

### TTRPG CLI Version

3.0.1

### Which Operating Systems have you experienced this on?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [x] Windows

### LINKED ISSUE #675: ID Block Error & Spelling Correction
1) Believe we need tp correct the spelling of Progession to Progression.

2) Also believe we need to add a line break between the Class Progression Table, and the ^class-progression Block-ID signifier. Currently the Block-ID is showing up as part of the table, adding the line break makes it act correctly as an ID in Markdown.

3?) Could be piggybacked with #672 in the lines just above, which I believe just needs the class feature href URL encoding removed and add a + "class = "internal link"" to the end of the href

IE; current non-working = 
a href='#Magic%20Item%20Master%20(Level%2018)'>Magic Item Master

Updated and working = 
a href='#Soul of Artifice (Level 20)'class="internal-link">Soul of Artifice

https://github.com/ebullient/ttrpg-convert-cli/blob/29c31d89d64776e615c28cd5baded9e7152d38ed/src/main/java/dev/ebullient/convert/tools/dnd5e/Json2QuteClass.java#L462

V3.0.1

Sorry, hope that all makes sense, and I'm explaining properly, first time using Github, and I'm using google to slowly expand my understanding, to try and help call out / fix the issues.

### PR DESCRIPTION
**Pull request by jboehm77**
Attempted to fix some low-hanging fruit that were within my limited capability. Seems to fix #675, fix #672, fix #655, fix #628, and fix #625. I also introduced some formatting enhancements for the properties section of spells (e.g. capitalization, pluralization, etc). If any of that seems unnecessary I can revert those changes.

### CODE REVIEW

File: src/main/java/dev/ebullient/convert/tools/dnd5e/Json2QuteClass.java [hunk 1]
```diff
@@ -905,9 +906,8 @@ void addSpellSlot(String value) {
         }
 
         String toHtmlLink(String x, String level) {
-            return String.format("<a href='#%s'>%s</a>",
-                    toAnchorTag(x + " (Level " + level + ")"),
-                    x);
+            return String.format("<a href='#%s'class=\"internal-link\">%s</a>",
```
Comment (ebullient) [inline src/main/java/dev/ebullient/convert/tools/dnd5e/Json2QuteClass.java:909]: HTML doesn't care about single or double quotes, and this is a little easier to read. Also, missed a space between href & class.

```suggestion
            return String.format("<a href='#%s' class='internal-link'>%s</a>",
```

File: src/main/java/dev/ebullient/convert/tools/dnd5e/Json2QuteClass.java [hunk 2]
```diff
@@ -905,9 +906,8 @@ void addSpellSlot(String value) {
...
+                    x + " (Level " + level + ")", x);
```
Comment (ebullient) [inline src/main/java/dev/ebullient/convert/tools/dnd5e/Json2QuteClass.java:910]: I don't understand this. I believe this needs to be converted to an anchor tag for this link to work (with %20 and whatnot).

File: src/main/java/dev/ebullient/convert/tools/dnd5e/Json2QuteItem.java [hunk 3]
```diff
@@ -346,7 +346,7 @@ void insertItemRefText(List<String> text, String input) {
                             rootNode.get("detail1").asText());
```
Comment (ebullient) [inline src/main/java/dev/ebullient/convert/tools/dnd5e/Json2QuteItem.java:346]: In theory, these should be changed to use the enum reference, instead of the old string lookup. I thought I'd fixed items.. but maybe I'm thinking of classes..

File: src/main/java/dev/ebullient/convert/tools/dnd5e/JsonTextReplacement.java [hunk 4]
```diff
@@ -326,7 +326,12 @@ default String _replaceTokenText(String input, boolean nested) {
                 } else if (match.group(1).contains("p")) {
                     method = "Power ";
                 }
-                return "*%s%sAttack:*".formatted(String.join("or ", type), method);
+
+                if (method == "") { // This is a little crude
```
Comment (ebullient) [inline src/main/java/dev/ebullient/convert/tools/dnd5e/JsonTextReplacement.java:330]:
```suggestion
                if (method.isBlank()) {
```

File: src/main/java/dev/ebullient/convert/tools/dnd5e/JsonTextReplacement.java [hunk 5]
```diff
@@ -326,7 +326,12 @@ default String _replaceTokenText(String input, boolean nested) {
...
+                    return "*%sAttack Roll:*".formatted(String.join("or ", type));
```
Comment (ebullient) [inline src/main/java/dev/ebullient/convert/tools/dnd5e/JsonTextReplacement.java:331]: There is a static method "joinConjunct") that will do this or thing. Also, you may need " or ".. ?

File: src/main/java/dev/ebullient/convert/tools/dnd5e/SpellEntry.java [hunk 6]
```diff
@@ -130,9 +130,9 @@ private List<String> spellComponents(JsonNode spellNode) {
                 case "s" -> list.add("S");
                 case "m" -> {
                     if (f.getValue().isObject()) {
-                        list.add(SpellIndexFields.text.replaceTextFrom(f.getValue(), converter));
+                        list.add("M (" + SpellIndexFields.text.replaceTextFrom(f.getValue(), converter) + ")");
```
Comment (ebullient) [inline src/main/java/dev/ebullient/convert/tools/dnd5e/SpellEntry.java:133]: You have this above, too.. but this might be a case where the formatted string is more readable (you can tell what the formatted string will like): 

"M (%s)".formatted(SpellIndexFields.text.replaceTextFrom(f.getValue(), converter));

Not necessary here, but that's why I do it.

Given this is used in a few places, you could create a short method:

```
list.add(materialComponents(f.getValue()));
```

```
String materialComponents(JsonNode source) {
return "M (%s)".formatted(
    source.isObject()
      ? SpellIndexFields.text.replaceTextFrom(source, converter)
      : converter.replaceText(source));
}
```

**Review by ebullient — CHANGES_REQUESTED** [review]

File: src/main/java/dev/ebullient/convert/tools/dnd5e/Json2QuteClass.java (hunk 2 above)
Comment (jboehm77) [reply src/main/java/dev/ebullient/convert/tools/dnd5e/Json2QuteClass.java:910]: That makes two of us because I don't get it either, but Obsidian manages to understand it in my tests. It could be an Obsidian-specific capability, and I didn't test it with the anchor tag + the internal link class at once, so I'll try that out.

File: src/main/java/dev/ebullient/convert/tools/dnd5e/SpellEntry.java (hunk 6 above)
Comment (jboehm77) [reply src/main/java/dev/ebullient/convert/tools/dnd5e/SpellEntry.java:133]: Thanks for this. I'm quite literally learning java as I dive into this so I tried simple updates first. Your suggestion makes sense and I'll toss this in when I find a moment.

File: src/main/java/dev/ebullient/convert/tools/dnd5e/Json2QuteClass.java (hunk 2 above)
Comment (ebullient) [reply src/main/java/dev/ebullient/convert/tools/dnd5e/Json2QuteClass.java:910]: https://github.com/ebullient/ttrpg-convert-cli/issues/675 .. hmm. It may be because this is in a table as an href, rather than a markdown link in text..

File: src/main/java/dev/ebullient/convert/tools/dnd5e/JsonTextReplacement.java (hunk 5 above)
Comment (jboehm77) [reply src/main/java/dev/ebullient/convert/tools/dnd5e/JsonTextReplacement.java:331]: This was just the way it was set up before, such that the trailing spaces were incorporated in `type` in the preceding lines, and didn't need to be inserted via the delimiter.

File: src/main/java/dev/ebullient/convert/tools/dnd5e/Json2QuteClass.java (hunk 2 above)
Comment (jboehm77) [reply src/main/java/dev/ebullient/convert/tools/dnd5e/Json2QuteClass.java:910]: So just tested with the anchor tag restored, and I see the following output when mousing over the entry `<a href='#Spellcasting%20(Level%201)' class='internal-link'>Spellcasting</a>` in read mode (note the file name is a copy that I made to be a template for homebrew classes, but format is still the same):

image

Despite the referenced heading actually existing in the same file:

image

Comment (ebullient) [reply src/main/java/dev/ebullient/convert/tools/dnd5e/Json2QuteClass.java:910]: Yea.. I think it is the anchor tag. Obsidian encodes the %20 from markdown into spaces in the anchor. I must not be testing href properly in my link checking..

**Review by ebullient — APPROVED** [review]

**Comment by jboehm77** [comment]
Didn't finish a few things. Will resolve everything in a bit.

File: src/main/java/dev/ebullient/convert/tools/dnd5e/Json2QuteItem.java (hunk 3 above)
Comment (jboehm77) [reply src/main/java/dev/ebullient/convert/tools/dnd5e/Json2QuteItem.java:346]: Sorry, I may be limited by my lack of experience. Was your suggestion here to add `detail1` and `resist` to the enum lower down in this file and then reference them with something like `getTextOrEmpty()`?

**Comment by ebullient** [comment]
LMK when you're ready ;)

**Comment by jboehm77** [comment]
> LMK when you're ready ;)

See comment on last unresolved issue above. Wasn't sure exactly what you wanted. Everything else should be good to go.

**Comment by jboehm77** [comment]
The comments should all be addressed now. Note I couldn't help myself when I saw some potentially better ways to implement my previous updates to spell casting times/durations. May want to review those again in case you happen to find anything you disagree with.

**Comment by jboehm77** [comment]
Not sure why the check is failing now and not before/in main. Only guess I have is something about how `formatted()` works?

**Comment by ebullient** [comment]
```
**Components:** V, S, M (a humanoid's corpse for each {@creature mindless corpse|FoxfireVamp} you intend to create; a small concoction of blood, phlegm and bile and two points from your blood pool which are consumed by the power)"
```

You need to make sure to call "replaceText" on the material value so that `{@..}` tag gets replaced with a link.

**Comment by jboehm77** [comment]
Can't believe I missed that when looking this over the other night. Should be fixed now 🤞

File: src/main/java/dev/ebullient/convert/tools/dnd5e/Json2QuteSpell.java [hunk 7]
```diff
@@ -111,10 +111,10 @@ String spellComponents() {
     }
 
     String materialComponents(JsonNode source) {
-        return "M (%s)".formatted(
+        return "M (%s)".formatted(replaceText(
                 source.isObject()
-                        ? SpellFields.text.getTextOrEmpty(source)
-                        : source.asText());
+                    ? SpellFields.text.getTextOrEmpty(source)
```
Comment (ebullient) [inline src/main/java/dev/ebullient/convert/tools/dnd5e/Json2QuteSpell.java:116]: FWIW, another option is:

```
return "M (%s)".formatted(
        source.isObject()
            ? SpellFields.text.replaceTextFrom(source, this)
            : replaceText(source)
        );
```

Comment (jboehm77) [reply src/main/java/dev/ebullient/convert/tools/dnd5e/Json2QuteSpell.java]: Implemented. And fixed the formatting failure (hopefully).
